#CORS
config:
  cors:
    url: http://localhost:4200, https://myindividualmanagement.netlify.app/ #${URL_CORS}

#JWT
security:
  jwt:
    tokenName: accessToken
    refreshName: refreshToken
    secretKey: a1b2c3d4e5f67890abcdef1234567890abcdef1234567890abcdef12345678 #${SECRET_KEY}

#Intercalation + Spring Session Redis
spring:
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    open-in-view: false
    
#Session server
server:
  servlet:
    session:
      timeout: 20m
      cookie:
        http-only: true